// Code generated by go-swagger; DO NOT EDIT.

package exception_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddExceptionNotificationParams creates a new AddExceptionNotificationParams object
// with the default values initialized.
func NewAddExceptionNotificationParams() *AddExceptionNotificationParams {
	var ()
	return &AddExceptionNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddExceptionNotificationParamsWithTimeout creates a new AddExceptionNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddExceptionNotificationParamsWithTimeout(timeout time.Duration) *AddExceptionNotificationParams {
	var ()
	return &AddExceptionNotificationParams{

		timeout: timeout,
	}
}

// NewAddExceptionNotificationParamsWithContext creates a new AddExceptionNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddExceptionNotificationParamsWithContext(ctx context.Context) *AddExceptionNotificationParams {
	var ()
	return &AddExceptionNotificationParams{

		Context: ctx,
	}
}

// NewAddExceptionNotificationParamsWithHTTPClient creates a new AddExceptionNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddExceptionNotificationParamsWithHTTPClient(client *http.Client) *AddExceptionNotificationParams {
	var ()
	return &AddExceptionNotificationParams{
		HTTPClient: client,
	}
}

/*AddExceptionNotificationParams contains all the parameters to send to the API endpoint
for the add exception notification operation typically these are written to a http.Request
*/
type AddExceptionNotificationParams struct {

	/*XGiantSwarmActivity
	  Name of an activity to track, like "list-clusters". This allows to
	analyze several API requests sent in context and gives an idea on
	the purpose.


	*/
	XGiantSwarmActivity *string
	/*XGiantSwarmCmdLine
	  If activity has been issued by a CLI, this header can contain the
	command line


	*/
	XGiantSwarmCmdLine *string
	/*XRequestID
	  A randomly generated key that can be used to track a request throughout
	services of Giant Swarm.


	*/
	XRequestID *string
	/*Body*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add exception notification params
func (o *AddExceptionNotificationParams) WithTimeout(timeout time.Duration) *AddExceptionNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add exception notification params
func (o *AddExceptionNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add exception notification params
func (o *AddExceptionNotificationParams) WithContext(ctx context.Context) *AddExceptionNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add exception notification params
func (o *AddExceptionNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add exception notification params
func (o *AddExceptionNotificationParams) WithHTTPClient(client *http.Client) *AddExceptionNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add exception notification params
func (o *AddExceptionNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXGiantSwarmActivity adds the xGiantSwarmActivity to the add exception notification params
func (o *AddExceptionNotificationParams) WithXGiantSwarmActivity(xGiantSwarmActivity *string) *AddExceptionNotificationParams {
	o.SetXGiantSwarmActivity(xGiantSwarmActivity)
	return o
}

// SetXGiantSwarmActivity adds the xGiantSwarmActivity to the add exception notification params
func (o *AddExceptionNotificationParams) SetXGiantSwarmActivity(xGiantSwarmActivity *string) {
	o.XGiantSwarmActivity = xGiantSwarmActivity
}

// WithXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the add exception notification params
func (o *AddExceptionNotificationParams) WithXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) *AddExceptionNotificationParams {
	o.SetXGiantSwarmCmdLine(xGiantSwarmCmdLine)
	return o
}

// SetXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the add exception notification params
func (o *AddExceptionNotificationParams) SetXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) {
	o.XGiantSwarmCmdLine = xGiantSwarmCmdLine
}

// WithXRequestID adds the xRequestID to the add exception notification params
func (o *AddExceptionNotificationParams) WithXRequestID(xRequestID *string) *AddExceptionNotificationParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the add exception notification params
func (o *AddExceptionNotificationParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the add exception notification params
func (o *AddExceptionNotificationParams) WithBody(body interface{}) *AddExceptionNotificationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add exception notification params
func (o *AddExceptionNotificationParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddExceptionNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XGiantSwarmActivity != nil {

		// header param X-Giant-Swarm-Activity
		if err := r.SetHeaderParam("X-Giant-Swarm-Activity", *o.XGiantSwarmActivity); err != nil {
			return err
		}

	}

	if o.XGiantSwarmCmdLine != nil {

		// header param X-Giant-Swarm-CmdLine
		if err := r.SetHeaderParam("X-Giant-Swarm-CmdLine", *o.XGiantSwarmCmdLine); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
