// Code generated by go-swagger; DO NOT EDIT.

package cluster_labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/v2/models"
)

// NewSetClusterLabelsParams creates a new SetClusterLabelsParams object
// with the default values initialized.
func NewSetClusterLabelsParams() *SetClusterLabelsParams {
	var ()
	return &SetClusterLabelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetClusterLabelsParamsWithTimeout creates a new SetClusterLabelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetClusterLabelsParamsWithTimeout(timeout time.Duration) *SetClusterLabelsParams {
	var ()
	return &SetClusterLabelsParams{

		timeout: timeout,
	}
}

// NewSetClusterLabelsParamsWithContext creates a new SetClusterLabelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetClusterLabelsParamsWithContext(ctx context.Context) *SetClusterLabelsParams {
	var ()
	return &SetClusterLabelsParams{

		Context: ctx,
	}
}

// NewSetClusterLabelsParamsWithHTTPClient creates a new SetClusterLabelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetClusterLabelsParamsWithHTTPClient(client *http.Client) *SetClusterLabelsParams {
	var ()
	return &SetClusterLabelsParams{
		HTTPClient: client,
	}
}

/*SetClusterLabelsParams contains all the parameters to send to the API endpoint
for the set cluster labels operation typically these are written to a http.Request
*/
type SetClusterLabelsParams struct {

	/*XGiantSwarmActivity
	  Name of an activity to track, like "list-clusters". This allows to
	analyze several API requests sent in context and gives an idea on
	the purpose.


	*/
	XGiantSwarmActivity *string
	/*XGiantSwarmCmdLine
	  If activity has been issued by a CLI, this header can contain the
	command line


	*/
	XGiantSwarmCmdLine *string
	/*XRequestID
	  A randomly generated key that can be used to track a request throughout
	services of Giant Swarm.


	*/
	XRequestID *string
	/*Body
	  Labels to attach to this cluster.

	*/
	Body *models.V5SetClusterLabelsRequest
	/*ClusterID
	  Cluster ID

	*/
	ClusterID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set cluster labels params
func (o *SetClusterLabelsParams) WithTimeout(timeout time.Duration) *SetClusterLabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set cluster labels params
func (o *SetClusterLabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set cluster labels params
func (o *SetClusterLabelsParams) WithContext(ctx context.Context) *SetClusterLabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set cluster labels params
func (o *SetClusterLabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set cluster labels params
func (o *SetClusterLabelsParams) WithHTTPClient(client *http.Client) *SetClusterLabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set cluster labels params
func (o *SetClusterLabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXGiantSwarmActivity adds the xGiantSwarmActivity to the set cluster labels params
func (o *SetClusterLabelsParams) WithXGiantSwarmActivity(xGiantSwarmActivity *string) *SetClusterLabelsParams {
	o.SetXGiantSwarmActivity(xGiantSwarmActivity)
	return o
}

// SetXGiantSwarmActivity adds the xGiantSwarmActivity to the set cluster labels params
func (o *SetClusterLabelsParams) SetXGiantSwarmActivity(xGiantSwarmActivity *string) {
	o.XGiantSwarmActivity = xGiantSwarmActivity
}

// WithXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the set cluster labels params
func (o *SetClusterLabelsParams) WithXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) *SetClusterLabelsParams {
	o.SetXGiantSwarmCmdLine(xGiantSwarmCmdLine)
	return o
}

// SetXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the set cluster labels params
func (o *SetClusterLabelsParams) SetXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) {
	o.XGiantSwarmCmdLine = xGiantSwarmCmdLine
}

// WithXRequestID adds the xRequestID to the set cluster labels params
func (o *SetClusterLabelsParams) WithXRequestID(xRequestID *string) *SetClusterLabelsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the set cluster labels params
func (o *SetClusterLabelsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the set cluster labels params
func (o *SetClusterLabelsParams) WithBody(body *models.V5SetClusterLabelsRequest) *SetClusterLabelsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set cluster labels params
func (o *SetClusterLabelsParams) SetBody(body *models.V5SetClusterLabelsRequest) {
	o.Body = body
}

// WithClusterID adds the clusterID to the set cluster labels params
func (o *SetClusterLabelsParams) WithClusterID(clusterID string) *SetClusterLabelsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the set cluster labels params
func (o *SetClusterLabelsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WriteToRequest writes these params to a swagger request
func (o *SetClusterLabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XGiantSwarmActivity != nil {

		// header param X-Giant-Swarm-Activity
		if err := r.SetHeaderParam("X-Giant-Swarm-Activity", *o.XGiantSwarmActivity); err != nil {
			return err
		}

	}

	if o.XGiantSwarmCmdLine != nil {

		// header param X-Giant-Swarm-CmdLine
		if err := r.SetHeaderParam("X-Giant-Swarm-CmdLine", *o.XGiantSwarmCmdLine); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
