// Code generated by go-swagger; DO NOT EDIT.

package app_configs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/v2/models"
)

// GetClusterAppConfigV5Reader is a Reader for the GetClusterAppConfigV5 structure.
type GetClusterAppConfigV5Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterAppConfigV5Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterAppConfigV5OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetClusterAppConfigV5Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetClusterAppConfigV5NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClusterAppConfigV5OK creates a GetClusterAppConfigV5OK with default headers values
func NewGetClusterAppConfigV5OK() *GetClusterAppConfigV5OK {
	return &GetClusterAppConfigV5OK{}
}

/*GetClusterAppConfigV5OK handles this case with default header values.

Success
*/
type GetClusterAppConfigV5OK struct {
	Payload models.V4GetClusterAppConfigResponse
}

func (o *GetClusterAppConfigV5OK) Error() string {
	return fmt.Sprintf("[GET /v5/clusters/{cluster_id}/apps/{app_name}/config/][%d] getClusterAppConfigV5OK  %+v", 200, o.Payload)
}

func (o *GetClusterAppConfigV5OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterAppConfigV5Unauthorized creates a GetClusterAppConfigV5Unauthorized with default headers values
func NewGetClusterAppConfigV5Unauthorized() *GetClusterAppConfigV5Unauthorized {
	return &GetClusterAppConfigV5Unauthorized{}
}

/*GetClusterAppConfigV5Unauthorized handles this case with default header values.

Permission denied
*/
type GetClusterAppConfigV5Unauthorized struct {
	Payload *models.V4GenericResponse
}

func (o *GetClusterAppConfigV5Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v5/clusters/{cluster_id}/apps/{app_name}/config/][%d] getClusterAppConfigV5Unauthorized  %+v", 401, o.Payload)
}

func (o *GetClusterAppConfigV5Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterAppConfigV5NotFound creates a GetClusterAppConfigV5NotFound with default headers values
func NewGetClusterAppConfigV5NotFound() *GetClusterAppConfigV5NotFound {
	return &GetClusterAppConfigV5NotFound{}
}

/*GetClusterAppConfigV5NotFound handles this case with default header values.

App Config not found
*/
type GetClusterAppConfigV5NotFound struct {
	Payload *models.V4GenericResponse
}

func (o *GetClusterAppConfigV5NotFound) Error() string {
	return fmt.Sprintf("[GET /v5/clusters/{cluster_id}/apps/{app_name}/config/][%d] getClusterAppConfigV5NotFound  %+v", 404, o.Payload)
}

func (o *GetClusterAppConfigV5NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
