// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/models"
)

// DeleteClusterAppV4Reader is a Reader for the DeleteClusterAppV4 structure.
type DeleteClusterAppV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClusterAppV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteClusterAppV4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteClusterAppV4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteClusterAppV4NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteClusterAppV4Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteClusterAppV4OK creates a DeleteClusterAppV4OK with default headers values
func NewDeleteClusterAppV4OK() *DeleteClusterAppV4OK {
	return &DeleteClusterAppV4OK{}
}

/*DeleteClusterAppV4OK handles this case with default header values.

App deleted
*/
type DeleteClusterAppV4OK struct {
	Payload *models.V4GenericResponse
}

func (o *DeleteClusterAppV4OK) Error() string {
	return fmt.Sprintf("[DELETE /v4/clusters/{cluster_id}/apps/{app_name}/][%d] deleteClusterAppV4OK  %+v", 200, o.Payload)
}

func (o *DeleteClusterAppV4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterAppV4Unauthorized creates a DeleteClusterAppV4Unauthorized with default headers values
func NewDeleteClusterAppV4Unauthorized() *DeleteClusterAppV4Unauthorized {
	return &DeleteClusterAppV4Unauthorized{}
}

/*DeleteClusterAppV4Unauthorized handles this case with default header values.

Permission denied
*/
type DeleteClusterAppV4Unauthorized struct {
	Payload *models.V4GenericResponse
}

func (o *DeleteClusterAppV4Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v4/clusters/{cluster_id}/apps/{app_name}/][%d] deleteClusterAppV4Unauthorized  %+v", 401, o.Payload)
}

func (o *DeleteClusterAppV4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterAppV4NotFound creates a DeleteClusterAppV4NotFound with default headers values
func NewDeleteClusterAppV4NotFound() *DeleteClusterAppV4NotFound {
	return &DeleteClusterAppV4NotFound{}
}

/*DeleteClusterAppV4NotFound handles this case with default header values.

App not found
*/
type DeleteClusterAppV4NotFound struct {
	Payload *models.V4GenericResponse
}

func (o *DeleteClusterAppV4NotFound) Error() string {
	return fmt.Sprintf("[DELETE /v4/clusters/{cluster_id}/apps/{app_name}/][%d] deleteClusterAppV4NotFound  %+v", 404, o.Payload)
}

func (o *DeleteClusterAppV4NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterAppV4Default creates a DeleteClusterAppV4Default with default headers values
func NewDeleteClusterAppV4Default(code int) *DeleteClusterAppV4Default {
	return &DeleteClusterAppV4Default{
		_statusCode: code,
	}
}

/*DeleteClusterAppV4Default handles this case with default header values.

Error
*/
type DeleteClusterAppV4Default struct {
	_statusCode int

	Payload *models.V4GenericResponse
}

// Code gets the status code for the delete cluster app v4 default response
func (o *DeleteClusterAppV4Default) Code() int {
	return o._statusCode
}

func (o *DeleteClusterAppV4Default) Error() string {
	return fmt.Sprintf("[DELETE /v4/clusters/{cluster_id}/apps/{app_name}/][%d] deleteClusterAppV4 default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteClusterAppV4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
