// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterAppsV4Params creates a new GetClusterAppsV4Params object
// with the default values initialized.
func NewGetClusterAppsV4Params() *GetClusterAppsV4Params {
	var ()
	return &GetClusterAppsV4Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterAppsV4ParamsWithTimeout creates a new GetClusterAppsV4Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClusterAppsV4ParamsWithTimeout(timeout time.Duration) *GetClusterAppsV4Params {
	var ()
	return &GetClusterAppsV4Params{

		timeout: timeout,
	}
}

// NewGetClusterAppsV4ParamsWithContext creates a new GetClusterAppsV4Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetClusterAppsV4ParamsWithContext(ctx context.Context) *GetClusterAppsV4Params {
	var ()
	return &GetClusterAppsV4Params{

		Context: ctx,
	}
}

// NewGetClusterAppsV4ParamsWithHTTPClient creates a new GetClusterAppsV4Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClusterAppsV4ParamsWithHTTPClient(client *http.Client) *GetClusterAppsV4Params {
	var ()
	return &GetClusterAppsV4Params{
		HTTPClient: client,
	}
}

/*GetClusterAppsV4Params contains all the parameters to send to the API endpoint
for the get cluster apps v4 operation typically these are written to a http.Request
*/
type GetClusterAppsV4Params struct {

	/*XGiantSwarmActivity
	  Name of an activity to track, like "list-clusters". This allows to
	analyze several API requests sent in context and gives an idea on
	the purpose.


	*/
	XGiantSwarmActivity *string
	/*XGiantSwarmCmdLine
	  If activity has been issued by a CLI, this header can contain the
	command line


	*/
	XGiantSwarmCmdLine *string
	/*XRequestID
	  A randomly generated key that can be used to track a request throughout
	services of Giant Swarm.


	*/
	XRequestID *string
	/*ClusterID
	  Cluster ID

	*/
	ClusterID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithTimeout(timeout time.Duration) *GetClusterAppsV4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithContext(ctx context.Context) *GetClusterAppsV4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithHTTPClient(client *http.Client) *GetClusterAppsV4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXGiantSwarmActivity adds the xGiantSwarmActivity to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithXGiantSwarmActivity(xGiantSwarmActivity *string) *GetClusterAppsV4Params {
	o.SetXGiantSwarmActivity(xGiantSwarmActivity)
	return o
}

// SetXGiantSwarmActivity adds the xGiantSwarmActivity to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetXGiantSwarmActivity(xGiantSwarmActivity *string) {
	o.XGiantSwarmActivity = xGiantSwarmActivity
}

// WithXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) *GetClusterAppsV4Params {
	o.SetXGiantSwarmCmdLine(xGiantSwarmCmdLine)
	return o
}

// SetXGiantSwarmCmdLine adds the xGiantSwarmCmdLine to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetXGiantSwarmCmdLine(xGiantSwarmCmdLine *string) {
	o.XGiantSwarmCmdLine = xGiantSwarmCmdLine
}

// WithXRequestID adds the xRequestID to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithXRequestID(xRequestID *string) *GetClusterAppsV4Params {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithClusterID adds the clusterID to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) WithClusterID(clusterID string) *GetClusterAppsV4Params {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get cluster apps v4 params
func (o *GetClusterAppsV4Params) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterAppsV4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XGiantSwarmActivity != nil {

		// header param X-Giant-Swarm-Activity
		if err := r.SetHeaderParam("X-Giant-Swarm-Activity", *o.XGiantSwarmActivity); err != nil {
			return err
		}

	}

	if o.XGiantSwarmCmdLine != nil {

		// header param X-Giant-Swarm-CmdLine
		if err := r.SetHeaderParam("X-Giant-Swarm-CmdLine", *o.XGiantSwarmCmdLine); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
