// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/v2/models"
)

// ModifyClusterAppV4Reader is a Reader for the ModifyClusterAppV4 structure.
type ModifyClusterAppV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyClusterAppV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyClusterAppV4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewModifyClusterAppV4BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewModifyClusterAppV4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewModifyClusterAppV4NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewModifyClusterAppV4Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewModifyClusterAppV4OK creates a ModifyClusterAppV4OK with default headers values
func NewModifyClusterAppV4OK() *ModifyClusterAppV4OK {
	return &ModifyClusterAppV4OK{}
}

/*ModifyClusterAppV4OK handles this case with default header values.

App modified
*/
type ModifyClusterAppV4OK struct {
	Payload *models.V4App
}

func (o *ModifyClusterAppV4OK) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/][%d] modifyClusterAppV4OK  %+v", 200, o.Payload)
}

func (o *ModifyClusterAppV4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4App)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppV4BadRequest creates a ModifyClusterAppV4BadRequest with default headers values
func NewModifyClusterAppV4BadRequest() *ModifyClusterAppV4BadRequest {
	return &ModifyClusterAppV4BadRequest{}
}

/*ModifyClusterAppV4BadRequest handles this case with default header values.

Invalid input
*/
type ModifyClusterAppV4BadRequest struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppV4BadRequest) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/][%d] modifyClusterAppV4BadRequest  %+v", 400, o.Payload)
}

func (o *ModifyClusterAppV4BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppV4Unauthorized creates a ModifyClusterAppV4Unauthorized with default headers values
func NewModifyClusterAppV4Unauthorized() *ModifyClusterAppV4Unauthorized {
	return &ModifyClusterAppV4Unauthorized{}
}

/*ModifyClusterAppV4Unauthorized handles this case with default header values.

Permission denied
*/
type ModifyClusterAppV4Unauthorized struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppV4Unauthorized) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/][%d] modifyClusterAppV4Unauthorized  %+v", 401, o.Payload)
}

func (o *ModifyClusterAppV4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppV4NotFound creates a ModifyClusterAppV4NotFound with default headers values
func NewModifyClusterAppV4NotFound() *ModifyClusterAppV4NotFound {
	return &ModifyClusterAppV4NotFound{}
}

/*ModifyClusterAppV4NotFound handles this case with default header values.

App not found
*/
type ModifyClusterAppV4NotFound struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppV4NotFound) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/][%d] modifyClusterAppV4NotFound  %+v", 404, o.Payload)
}

func (o *ModifyClusterAppV4NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppV4Default creates a ModifyClusterAppV4Default with default headers values
func NewModifyClusterAppV4Default(code int) *ModifyClusterAppV4Default {
	return &ModifyClusterAppV4Default{
		_statusCode: code,
	}
}

/*ModifyClusterAppV4Default handles this case with default header values.

error
*/
type ModifyClusterAppV4Default struct {
	_statusCode int

	Payload *models.V4GenericResponse
}

// Code gets the status code for the modify cluster app v4 default response
func (o *ModifyClusterAppV4Default) Code() int {
	return o._statusCode
}

func (o *ModifyClusterAppV4Default) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/][%d] modifyClusterAppV4 default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyClusterAppV4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
