// Code generated by go-swagger; DO NOT EDIT.

package app_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/models"
)

// GetClusterAppSecretV4Reader is a Reader for the GetClusterAppSecretV4 structure.
type GetClusterAppSecretV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterAppSecretV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterAppSecretV4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetClusterAppSecretV4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetClusterAppSecretV4NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClusterAppSecretV4OK creates a GetClusterAppSecretV4OK with default headers values
func NewGetClusterAppSecretV4OK() *GetClusterAppSecretV4OK {
	return &GetClusterAppSecretV4OK{}
}

/*GetClusterAppSecretV4OK handles this case with default header values.

Success
*/
type GetClusterAppSecretV4OK struct {
	Payload models.V4GetClusterAppSecretResponse
}

func (o *GetClusterAppSecretV4OK) Error() string {
	return fmt.Sprintf("[GET /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] getClusterAppSecretV4OK  %+v", 200, o.Payload)
}

func (o *GetClusterAppSecretV4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterAppSecretV4Unauthorized creates a GetClusterAppSecretV4Unauthorized with default headers values
func NewGetClusterAppSecretV4Unauthorized() *GetClusterAppSecretV4Unauthorized {
	return &GetClusterAppSecretV4Unauthorized{}
}

/*GetClusterAppSecretV4Unauthorized handles this case with default header values.

Permission denied
*/
type GetClusterAppSecretV4Unauthorized struct {
	Payload *models.V4GenericResponse
}

func (o *GetClusterAppSecretV4Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] getClusterAppSecretV4Unauthorized  %+v", 401, o.Payload)
}

func (o *GetClusterAppSecretV4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterAppSecretV4NotFound creates a GetClusterAppSecretV4NotFound with default headers values
func NewGetClusterAppSecretV4NotFound() *GetClusterAppSecretV4NotFound {
	return &GetClusterAppSecretV4NotFound{}
}

/*GetClusterAppSecretV4NotFound handles this case with default header values.

Secret not found
*/
type GetClusterAppSecretV4NotFound struct {
	Payload *models.V4GenericResponse
}

func (o *GetClusterAppSecretV4NotFound) Error() string {
	return fmt.Sprintf("[GET /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] getClusterAppSecretV4NotFound  %+v", 404, o.Payload)
}

func (o *GetClusterAppSecretV4NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
