// Code generated by go-swagger; DO NOT EDIT.

package app_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/giantswarm/gsclientgen/models"
)

// ModifyClusterAppSecretV4Reader is a Reader for the ModifyClusterAppSecretV4 structure.
type ModifyClusterAppSecretV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyClusterAppSecretV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyClusterAppSecretV4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewModifyClusterAppSecretV4BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewModifyClusterAppSecretV4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewModifyClusterAppSecretV4Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewModifyClusterAppSecretV4OK creates a ModifyClusterAppSecretV4OK with default headers values
func NewModifyClusterAppSecretV4OK() *ModifyClusterAppSecretV4OK {
	return &ModifyClusterAppSecretV4OK{}
}

/*ModifyClusterAppSecretV4OK handles this case with default header values.

Success
*/
type ModifyClusterAppSecretV4OK struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppSecretV4OK) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] modifyClusterAppSecretV4OK  %+v", 200, o.Payload)
}

func (o *ModifyClusterAppSecretV4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppSecretV4BadRequest creates a ModifyClusterAppSecretV4BadRequest with default headers values
func NewModifyClusterAppSecretV4BadRequest() *ModifyClusterAppSecretV4BadRequest {
	return &ModifyClusterAppSecretV4BadRequest{}
}

/*ModifyClusterAppSecretV4BadRequest handles this case with default header values.

Invalid input
*/
type ModifyClusterAppSecretV4BadRequest struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppSecretV4BadRequest) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] modifyClusterAppSecretV4BadRequest  %+v", 400, o.Payload)
}

func (o *ModifyClusterAppSecretV4BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppSecretV4Unauthorized creates a ModifyClusterAppSecretV4Unauthorized with default headers values
func NewModifyClusterAppSecretV4Unauthorized() *ModifyClusterAppSecretV4Unauthorized {
	return &ModifyClusterAppSecretV4Unauthorized{}
}

/*ModifyClusterAppSecretV4Unauthorized handles this case with default header values.

Permission denied
*/
type ModifyClusterAppSecretV4Unauthorized struct {
	Payload *models.V4GenericResponse
}

func (o *ModifyClusterAppSecretV4Unauthorized) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] modifyClusterAppSecretV4Unauthorized  %+v", 401, o.Payload)
}

func (o *ModifyClusterAppSecretV4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyClusterAppSecretV4Default creates a ModifyClusterAppSecretV4Default with default headers values
func NewModifyClusterAppSecretV4Default(code int) *ModifyClusterAppSecretV4Default {
	return &ModifyClusterAppSecretV4Default{
		_statusCode: code,
	}
}

/*ModifyClusterAppSecretV4Default handles this case with default header values.

Error
*/
type ModifyClusterAppSecretV4Default struct {
	_statusCode int

	Payload *models.V4GenericResponse
}

// Code gets the status code for the modify cluster app secret v4 default response
func (o *ModifyClusterAppSecretV4Default) Code() int {
	return o._statusCode
}

func (o *ModifyClusterAppSecretV4Default) Error() string {
	return fmt.Sprintf("[PATCH /v4/clusters/{cluster_id}/apps/{app_name}/secret/][%d] modifyClusterAppSecretV4 default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyClusterAppSecretV4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V4GenericResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
