/*
 * The Giant Swarm API
 *
 * This is the documentation for the Giant Swarm API.  For an introduction to Giant Swarm, refer to the [documentation site](https://docs.giantswarm.io/).  The Giant Swarm API attempts to behave in a __restful__ way. As a developer, you access resources using the `GET` method and, for example, delete them using the same path and the `DELETE` method.  Accessing resources via GET usually returns all information available about a resource, while collections, like for example the list of all clusters you have access to, only contain a selected few attributes of each member item.  Some requests, like for example the request to create a new cluster, don't return the resource itself. Instead, the response delivers a standard message body, showing a `code` and a `message` part. The `message` contains information for you or a client's end user. The `code` attribute contains some string (example: `RESOURCE_CREATED`) that is supposed to give you details on the state of the operation, in addition to standard HTTP status codes. This message format is also used in the case of errors. We provide a [list of all response codes](https://github.com/giantswarm/api-spec/blob/master/details/RESPONSE_CODES.md) outside this documentation.  Feedback on the API as well as this documentation is welcome via `support@giantswarm.io` or on IRC channel [#giantswarm](irc://irc.freenode.org:6667/#giantswarm) on freenode.  ## Source  The source of this documentation is available on [GitHub](https://github.com/giantswarm/api-spec). 
 *
 * API version: 4.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V5ClusterDetailsResponse struct {
	// Unique cluster identifier
	Id string `json:"id,omitempty"`
	// URI of the Kubernetes API endpoint
	ApiEndpoint string `json:"api_endpoint,omitempty"`
	// Date/time of cluster creation
	CreateDate string `json:"create_date,omitempty"`
	// Name of the organization owning the cluster 
	Owner string `json:"owner,omitempty"`
	// Cluster name
	Name string `json:"name,omitempty"`
	// ID of the credentials used to operate the cluster. See [Set credentials](#operation/addCredentials) for details. 
	CredentialId string `json:"credential_id,omitempty"`
	// The [release](https://docs.giantswarm.io/api/#tag/releases) version used by the cluster 
	ReleaseVersion string `json:"release_version,omitempty"`
	Master V5ClusterDetailsResponseMaster `json:"master,omitempty"`
	// List of conditions the cluster has gone through
	Conditions []V5ClusterDetailsResponseConditions `json:"conditions,omitempty"`
	Versions []V5ClusterDetailsResponseVersions `json:"versions,omitempty"`
}
