// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V5AddClusterRequestMasterNodes Defines how many master nodes the cluster should have.
//
// swagger:model v5AddClusterRequestMasterNodes
type V5AddClusterRequestMasterNodes struct {

	// Specifies whether or not this cluster should run with redundant master
	// nodes (high availability). When true, three master nodes will be started,
	// each one in a different availability zone that is selected randomly.
	// This is the recommended setting for production clusters. When false, only
	// one master node will be created, also in a randomly selected availability
	// zone.
	//
	HighAvailability *bool `json:"high_availability,omitempty"`
}

// Validate validates this v5 add cluster request master nodes
func (m *V5AddClusterRequestMasterNodes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V5AddClusterRequestMasterNodes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5AddClusterRequestMasterNodes) UnmarshalBinary(b []byte) error {
	var res V5AddClusterRequestMasterNodes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
