// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V5GetNodePoolsResponseItemsNodeSpecAzure Attributes specific to the Azure provider
//
// swagger:model v5GetNodePoolsResponseItemsNodeSpecAzure
type V5GetNodePoolsResponseItemsNodeSpecAzure struct {

	// spot instances
	SpotInstances *V5GetNodePoolsResponseItemsNodeSpecAzureSpotInstances `json:"spot_instances,omitempty"`

	// Azure virtual machine size used by all nodes in this pool.
	//
	VMSize string `json:"vm_size,omitempty"`
}

// Validate validates this v5 get node pools response items node spec azure
func (m *V5GetNodePoolsResponseItemsNodeSpecAzure) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpotInstances(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V5GetNodePoolsResponseItemsNodeSpecAzure) validateSpotInstances(formats strfmt.Registry) error {

	if swag.IsZero(m.SpotInstances) { // not required
		return nil
	}

	if m.SpotInstances != nil {
		if err := m.SpotInstances.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("spot_instances")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V5GetNodePoolsResponseItemsNodeSpecAzure) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5GetNodePoolsResponseItemsNodeSpecAzure) UnmarshalBinary(b []byte) error {
	var res V5GetNodePoolsResponseItemsNodeSpecAzure
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
