// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V5ListClustersByLabelRequest v5 list clusters by label request
// swagger:model v5ListClustersByLabelRequest
type V5ListClustersByLabelRequest struct {

	// Label selector
	//
	// The label selector string for filtering the clusters
	// Required: true
	Labels *string `json:"labels"`
}

// Validate validates this v5 list clusters by label request
func (m *V5ListClustersByLabelRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V5ListClustersByLabelRequest) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("labels", "body", m.Labels); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V5ListClustersByLabelRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5ListClustersByLabelRequest) UnmarshalBinary(b []byte) error {
	var res V5ListClustersByLabelRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
