// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V5ModifyClusterRequestMasterNodes v5 modify cluster request master nodes
// swagger:model v5ModifyClusterRequestMasterNodes
type V5ModifyClusterRequestMasterNodes struct {

	// Setting this attribute to `true` allows to switch a cluster from
	// using a single master node to multiple (3) master nodes in
	// separate availability zones for high availability. Note that the
	// switch from multiple master nodes to a single master node is not
	// supported.
	//
	HighAvailability bool `json:"high_availability,omitempty"`
}

// Validate validates this v5 modify cluster request master nodes
func (m *V5ModifyClusterRequestMasterNodes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V5ModifyClusterRequestMasterNodes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5ModifyClusterRequestMasterNodes) UnmarshalBinary(b []byte) error {
	var res V5ModifyClusterRequestMasterNodes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
